### PR TITLE
feat: Leaderboard design Improvement

### LINKED ISSUE #467: [FEATURE] Improve the Leaderboard Design [FEATURE] CTF Design Improvement, {branch: dev}.
### Detailed description

note: **branch: dev**, while forking, make sure to uncheck <u>*copy only main branch* </u> to get the dev branch in your fork
url: https://www.thecyberhub.org/leaderboard
image

[](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/a73b241c-74e9-4f80-946d-bd1363a3f75c)

### Context

Improvement In Leaderboard section

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by itsankitbhusal**
## Fixes Issue
Closes #467

## Changes proposed

The leaderboard table is refined with UX in mind, letting the table columns **Rank** and **Users** be aligned at the start which increases the readability, the column **Points** is right aligned as it will be easier for users to compare the values with other users. Additionally, I added a **hover effect on table row**  which will increase readability. Padding in the **x-axis** in the table body is fixed.
- Added two styled-components
     1. LeaderboardTableHeaderPoints
     2. LeaderboardTablePoints
- Added hover effect on a table row
- Added text-align to start for **Rank** and **Users** column and text-align to right for **Points** column
- Padding on **x-axis** fixed for table body rows

## Screenshots
Screenshot from 2023-10-08 15-59-56

## Code of Conduct

- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by kabir0x23 — CHANGES_REQUESTED** [review]
Hey

hey, rank and points part looks good but, users are not , because of crown

just a questions, can uu make design like this?
image

You can remove left crown from the username aswell

if u have any doubts or questions, feel free to ask

Thank  yyou..

**Comment by itsankitbhusal** [comment]
> Hey
> 
> hey, rank and points part looks good but, users are not , because of crown
> 
> just a questions, can uu make design like this? image
> 
> You can remove left crown from the username aswell
> 
> if u have any doubts or questions, feel free to ask
> 
> Thank yyou..

You mean to show trophy icon on left of the rank position right ?

I will work on this...

**Comment by kabir0x23** [comment]
> > Hey
> > hey, rank and points part looks good but, users are not , because of crown
> > just a questions, can uu make design like this? image
> > You can remove left crown from the username aswell
> > if u have any doubts or questions, feel free to ask
> > Thank yyou..
> 
> You mean to show trophy icon on left of the rank position right ?
> 
> I will work on this...

tropy is different crown is different, we can show golden one for 1, and same color for rest of those, and then there is no need for crown for top 1

and can you also make the same design that i have mentiond, here we just have to give padding, and margins with some light colors..

**Comment by itsankitbhusal** [comment]
UI fixed with your guidelines as mentioned.
screenshots:
Leaderboard section:
image
CTF page:
image
image

If there is any other things needs to be changed, please mention it.

**Review by kabir0x23 — APPROVED** [review]

**Comment by kabir0x23** [comment]
Thanks for contributing to Thecyberworld Community

**Pull request merged**
