### PR TITLE
fix | Fix Failed Stacked Barchart

### PR DESCRIPTION
**Pull request by duokobia**
This ticket was used to fix the failed stacked barcharts issue experienced during deployment upon completion of the analytics page #703. Please see snapshot below:

## Screenshots
Refactored Horizontal Barcharts

## Code of Conduct

- [ ] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by ArkadiK94** [comment]
image

It looks different on my screen. The problem is that the AnalyticsDoughnutChart is not in the center.

**Review by ArkadiK94 — APPROVED** [review]
@duokobia looks great, only one comment, what I wrote in the comment before.

**Comment by duokobia** [comment]
What browser do you use please?

**Comment by ArkadiK94** [comment]
I changed it because you don't see the problem in your screen so it is hard to adapt the code.

image

**Comment by ArkadiK94** [comment]
@duokobia Great work, thank you 👍

**Pull request merged**
