### PR TITLE
Storybook usage contributing file

### PR DESCRIPTION
**Pull request by Tamir198**
Added storybook usage guide to the readme. 

@ArkadiK94  @kabir0x23  Would love your point of view on this one

### CODE REVIEW

**Comment by Tamir198** [comment]
You can check the way it looks [here](https://github.com/Tamir198/TheCyberHUB/blob/storybook-usage-contributing-file/CONTRIBUTING.md)

**Comment by ArkadiK94** [comment]
Write the script 'npm run storybook' instead

**Comment by ArkadiK94** [comment]
I liked the example but I am not sure that it needs to be there. Maybe add a link to storybook docs instead. 
@kabir0x23 what do you think?

**Comment by ArkadiK94** [comment]
@Tamir198 I think putting an example can mislead contributors to think that this is the exact way and they may not understand what parts are needed and what not. Let's put link to the docs of storybook instead.

**Comment by Tamir198** [comment]
@ArkadiK94  How are the new changes?

**Comment by ArkadiK94** [comment]
>Write the script 'npm run storybook' instead

@Tamir198  You missed one comment

**Comment by ArkadiK94** [comment]
@Tamir198 Great, thanks :)

**Pull request merged**
