### PR TITLE
style: public profile | Icon bug fixed

### LINKED ISSUE #688: [Style] Public Profile | Fix Fire Icon Place
### Describe the bug

Fix fire icon placement 

### To Reproduce

Log in
Go to public profile

### Expected Behavior

The fire icon should be left to number (the number of Streak)

### Screenshot/ Video

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Riyazul555**
## Code of Conduct

- [ ] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by Riyazul555** [comment]
Fixes issue #688  

Screenshot (660)


Take a look @ArkadiK94

**Comment by ArkadiK94** [comment]
@kabir0x23 what do you think?

**Comment by ArkadiK94** [comment]
@Riyazul555 In my opinion, the number should stay in the middle and please put the icon in left to the number ( the other side)

**Comment by ArkadiK94** [comment]
@Riyazul555 hi, do you work on it?

**Comment by ArkadiK94** [comment]
image
@kabir0x23 He didn't response to me, so I did it. what do you think?

**Comment by ArkadiK94** [comment]
image

@kabir0x23 could you review it?

**Comment by kabir0x23** [comment]
looking good

**Pull request merged**
