### PR TITLE
feat: community events | event details page

### PR DESCRIPTION
**Pull request by ArkadiK94**
## Fixes Issue
related to issue #564

## Changes proposed
- [x] add route to event details page
- [x] show details of event , date, name, description, participants , link (only for users that joined the event)

## Screenshots

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/a493c41a-03ad-4d4d-9e56-eef61c72a3ee

## Note to reviewers
Next time, I will work on the option to add / display timeline of speakers and activities which I will display in this page

## Code of Conduct

- [X] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by kabir0x23** [comment]
can we make a open/view event button side to join button

what do you think?

**Comment by ArkadiK94** [comment]
Yup, I agree with you. I will add it instead of this icon.

**Comment by ArkadiK94** [comment]
@kabir0x23 how does it look now?

image

**Comment by kabir0x23** [comment]
awesome

**Pull request merged**
