### PR TITLE
feat: Explore | Show Only Users That Connected With Current User

### LINKED ISSUE #604: [FEATURE] Explore | Show Only Users That Connected With Current User (you)
### Detailed description

https://dev.thecyberhub.org/#/explore

Click Explore Tab

- [ ] add filter for "connections" , "following" , "followers", "all"

### Context

Users could explore the relevant users for them.

### Possible implementation

About All Users : We already have a component of my connections, we can use the same function/design for view all users. 

### Additional information

@kabir0x23 What do you say about making a filter as I wrote upwards?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sumanjeet0012**
## Fixes Issue

closes #604 

## Changes proposed

four new arrays (allusers, following, follower, connection) are created having userId of users and only that data is shown whose userId are present in the new created array.
In this way filter option is implemented.

I am facing a small issue.
when the page reloads then it is not showing any data , but when I click on any filter buttons after that it works fine. It looks like It is trying to access the data before it is even loaded.

## Screenshots

image

## Code of Conduct

- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by ArkadiK94** [comment]
@sumanjeet0012 I change this issue to draft because it is still in progress tell me when you will finish with it so we could review it.

**Comment by ArkadiK94** [comment]
@kabir0x23 the issue fixed :)

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/09267f1b-d619-4e44-bdd4-e7c90c6d163d

**Comment by ArkadiK94** [comment]
fix: show ctf which regiestered by filter (connections/followers/following)

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/5ae52faa-32bb-4312-aee0-c309f391da96

@kabir0x23

**Comment by kabir0x23** [comment]
awesome 😀

**Pull request merged**
