### PR TITLE
Fixed multiple select label color

### PR DESCRIPTION
**Pull request by Tamir198**
This is regarding my last pr starting to fix storybook , @ArkadiK94  

image

BTW - where can I find this component in the project ? I wanna make sure that its looking good on the actual project as well

### CODE REVIEW

**Comment by ArkadiK94** [comment]
@Tamir198 admin dashboard -> events -> create event -> add timeline

**Comment by Tamir198** [comment]
@ArkadiK94  I don't think that I have access to the admin dashboard. can you check that everything looks fine?

**Comment by kabir0x23** [comment]
i gave u the team access, logout and login , u will get

**Comment by Tamir198** [comment]
@ArkadiK94  Checked and the admin dashboard looks good as well

**Comment by ArkadiK94** [comment]
@Tamir198 The label here should be limited to one word, for now I only changed to "Label" but later on we should make validation here as well

**Pull request merged**
