### PR TITLE
fest: Team Page Base

### PR DESCRIPTION
**Pull request by AhmedKarray005**
## Screenshots

https://github.com/thecyberworld/TheCyberHUB/assets/104280658/1638a85e-eee3-4aef-b353-8e3957741c1d

## Code of Conduct

-   [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/TheCyberHUB/blob/dev/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

-   [x] My code follows the code style of this project.
-   [ ] My change requires changes to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [x] All new and existing tests passed.
-   [x] This PR does not contain plagiarized content.
-   [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by Tamir198 — COMMENTED** [review]
Hey, not sure about the style guides for this project but I would start by removing all the comments from the CSS files.

**Comment by kabir0x23** [comment]
> Hey, not sure about the style guides for this project but I would start by removing all the comments from the CSS files.

hi we use styled components,. u can use that strucutre

**Comment by ArkadiK94** [comment]
> > Hey, not sure about the style guides for this project but I would start by removing all the comments from the CSS files.
> 
> hi we use styled components,. u can use that strucutre

@AhmedKarray005 Could you move the styles from css file and use styled-components?

**Comment by AhmedKarray005** [comment]
@ArkadiK94 hello , can u maybe pull my work and open a new issue so that someone else can work on it?

**Comment by ArkadiK94** [comment]
@AhmedKarray005 ok, I will review the pr with the way you wrote inside css file and notify you if there are required changes to do before merging.

**Comment by ArkadiK94** [comment]
@AhmedKarray005 However, for your next pr, you should use styled components.

**Comment by AhmedKarray005** [comment]
okay understood

**Comment by ArkadiK94** [comment]
@AhmedKarray005 did you install a new package? if so, please commit the package.json and package-lock.json files
image

**Comment by AhmedKarray005** [comment]
@ArkadiK94 u can run this cmd npm install  @fortawesome/react-fontawesome @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons

**Comment by ArkadiK94** [comment]
@AhmedKarray005 I know how to fix it. The question, why didn't you commit the package.json file?

**Comment by AhmedKarray005** [comment]
@ArkadiK94 u want me to commit them?

**Comment by ArkadiK94** [comment]
@AhmedKarray005 Yes, when you install new packages you have to commit the package.json and package-lock.json files as well.

**Comment by AhmedKarray005** [comment]
@ArkadiK94 it is all good now

**Comment by kabir0x23** [comment]
@AhmedKarray005 hi, we are using this https://react-icons.github.io/react-icons/ for icons

see i u can find those icons u want here

and u can replace with font awesome

**Comment by AhmedKarray005** [comment]
@ArkadiK94 done , i updated them

**Comment by ArkadiK94** [comment]
@AhmedKarray005 Thanks, I will review the actual code and let you know :)

**Pull request merged**
