### PR TITLE
fix-username and date overlapping

### LINKED ISSUE #707: Overlap of Username and Creation Date in Feed Section for Long Usernames
### Describe the bug

When viewing the feed section, if a post is made by a user with a long username, the username overlaps with the date of creation, making both pieces of information hard to read. This issue affects the usability and aesthetic appeal of the feed section.

### To Reproduce

Go to the feed section.
Find a post by a user with a long username.
Observe that the username overlaps with the date of creation.

### Expected Behavior

The username and the date of creation should be displayed without overlapping, regardless of the username length. This might involve truncating the username, adjusting the layout, or implementing a responsive design to accommodate longer text.

### Screenshot/ Video

Screenshot 2024-03-07 at 10 47 22

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by iiDaVoDkA**
## Fixes Issue

closes #707

## Screenshots

Screenshot 2024-03-07 at 10 56 32

## Code of Conduct

- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by kabir0x23** [comment]
good but it is looking, wierd

image

**Comment by ArkadiK94** [comment]
image

1. he meant the dot left, the date should be in right corner
2. when I write a long name something break.

**Comment by iiDaVoDkA** [comment]
@ArkadiK94 
like this?

Screenshot 2024-03-09 at 23 32 52

this is an example for longer names 

Screenshot 2024-03-09 at 23 32 04

**Comment by ArkadiK94** [comment]
In the below example the dot moves too much.
@kabir0x23 is it ok to remove this dot? I think it will look better without it.

**Comment by kabir0x23** [comment]
> In the below example the dot moves too much. @kabir0x23 is it ok to remove this dot? I think it will look better without it.

yes we can remove the dot

**Review by ArkadiK94 — APPROVED** [review]
@iiDaVoDkA Thanks for your contribution , it looks great 👍

**Pull request merged**
