### PR TITLE
feat: contact form | Sumbitted succefully mechanism

### LINKED ISSUE #696: [Submitted successfully mechanism] <the form remains in a "submit successfully" state indefinitely>(in the internship opportunities section)
### Detailed description

After submitting the contact form successfully, the form remains in a "submit successfully" state indefinitely. Users are unable to submit another form unless they reload the page. This behavior could confuse users and prevent multiple submissions from the same session.

Expected behavior: After a successful submission, the form should either reset automatically after a certain period or provide a clear way for the user to reset the form manually.

Actual behavior: The form remains in a "successfully submitted" state with no clear way to reset or submit a new form without reloading the page.

### Context

Improving the form's usability by allowing users to make multiple submissions easily without confusion or the need to reload the page enhances the overall user experience.

### Possible implementation

1.Automatic Reset: Implement a timeout to automatically reset the form state (including the `isSuccess` state) after a successful submission.

.then((response) => {
    if (response.data.message === "Form submitted successfully") {
        setIsLoading(false);
        setIsSuccess(true);
       *new* setTimeout(() => {
            setIsSuccess(false); // Allow the user to submit the form again
        }, 5000); // Reset after 5 seconds
    }
})

2.Manual Reset: Provide a "Submit another response" button that allows users to manually reset the form to its initial state after a successful submission.

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by iiDaVoDkA**
## Fixes Issue

Closes #696

## Screenshots

Screenshot 2024-03-04 at 11 12 43

## Code of Conduct

- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [] My change requires changes to the documentation.
- [] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by ArkadiK94** [comment]
- this not related to this pr, but small changes that should be done, if you want, we can open new issue about it.
          - text color of placeholder should be gray and not white 
          - "Submitted" in past because that form was already submitted.

**Review by ArkadiK94 — DISMISSED** [review]
@iiDaVoDkA Great, thanks for your contribution 👍 
Tell me if you would like to make those two small changes in this pr.

**Comment by iiDaVoDkA** [comment]
sorry but i did not quite understand here i ve added a button to reset the form (2.Manual Reset: Provide a "Submit another response" button that allows users to manually reset the form to its initial state after a successful submission.

https://github.com/thecyberworld/TheCyberHUB/assets/147496071/cd997c66-a4ab-43f4-899d-291b2a4b50ce

)

**Comment by ArkadiK94** [comment]
Yup, this is not related to your changes, sorry for the confusion.

**Comment by ArkadiK94** [comment]
@iiDaVoDkA I tried it out, and I have a strange ux feeling.
I know that I told you to go with the reset button but : 
1. why do we need the upper button if it does not do anything...
2. when user clicks submit the fields are reset then if you will write something in the inputs and clicks "Submit Another Response" it will do a reset again, very strange.

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/4cfee321-051c-49eb-a284-d2e6a2ea1448


I have a different idea, let's do something else: when user clicks submit it will toast a message that the form was submitted and will reset the form and button will stay "Submit" all the time...

note: do git pull to get the updated styles.

**Comment by iiDaVoDkA** [comment]
do you want something like this

https://github.com/thecyberworld/TheCyberHUB/assets/147496071/d8e44678-8e5e-4831-9ba5-ed8826063775

**Comment by ArkadiK94** [comment]
@iiDaVoDkA yes, and remove the button "Submitted Successfully" we don't need it.

**Comment by iiDaVoDkA** [comment]
@ArkadiK94  like this?

https://github.com/thecyberworld/TheCyberHUB/assets/147496071/87472ebc-38bf-46cc-804e-b3fd5ca02b2f

**Review by ArkadiK94 — APPROVED** [review]
@iiDaVoDkA Great work, thank you for your contribution 👍

**Pull request merged**
