### PR TITLE
feat: community chat frontend

### LINKED ISSUE #482: [FEATURE] Community Chat Frontend Only, {branch: dev}.
### Detailed description

[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

Make sure to create a branch from dev branch
Under Dashboard > Community:
image

### Context

with this community will stay in network with each other

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by insane-22**
## Fixes Issue

Closes #482 

## Screenshots
Video Of changes:- 
https://github.com/thecyberworld/TheCyberHUB/assets/116253210/e9a8d024-0716-4c70-8efc-5f0786c82a5e

## Note to reviewers
I've added only frontend required for a chat feature, kindly check. 

## Code of Conduct

- [ ] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by kabir0x23** [comment]
i think u have missed the installation guide, am right?

**Comment by insane-22** [comment]
Ah yes, I sincerely apologise overlooking the installation guide, how shall I proceed further, shall I redo the work and submit another oull request?

**Comment by kabir0x23** [comment]
> Ah yes, I sincerely apologise overlooking the installation guide, how shall I proceed further, shall I redo the work and submit another oull request?

no issues 

so what u can do, store these changes somewhere else, do the installation step again, then move your changes there

**Comment by kabir0x23** [comment]
i have fixed the issues, u can continue if u want to work more on this feature like chat messages content if u want 

let me know once

thank you.,

**Comment by insane-22** [comment]
Thank you @kabir0x23, really appreciate your invaluable help.
But I got a little confused, what actually am I supposed to do?

**Comment by kabir0x23** [comment]
> Thank you @kabir0x23, really appreciate your invaluable help. But I got a little confused, what actually am I supposed to do?

like we have to build the community chat here,

u can ask for chatgpt for dummy chat data for communuty chat with channel names

exmaple will be look like this
{
channel: "general",
messages: {
kabir: "hi",
insane: "hi",
}
}


this is just example, this wont work

now we can map thrugh this json data and this data will be displayed as chats here

we are working on backend will connect by ourselves here later 


if sill having questions, feel free to ask here,

thankyou,

**Comment by insane-22** [comment]
Ok, I understand it now, but I am quite unsure  if I would be able to do it since I haven't done a similar thing before.

**Comment by kabir0x23** [comment]
> Ok, I understand it now, but I am quite unsure if I would be able to do it since I haven't done a similar thing before.

it's very simple see

first simply create one ChatMessage.jsx
ChatMessageElements.jsx for it's css
create this design there
image

time, username, image, and chat message 

then we will map that data from json and this will ready

save this data in chatData.jsx
```js
// chatData.js
const chatData = {
  channels: [
    {
      channelname: "General Chat",
      id: "1",
      messages: [
        {
          time: "2023-10-18T10:15:00",
          username: "Alice",
          image: "avatar-alice.jpg",
          message: "Hello, everyone! How's it going?"
        },
        {
          time: "2023-10-18T10:20:00",
          username: "Bob",
          image: "avatar-bob.jpg",
          message: "Hey, Alice! I'm doing great. How about you?"
        }
        // Add more messages for the General Chat channel
      ]
    },
    {
      channelname: "Help",
      id: "2",
      messages: [
        {
          time: "2023-10-18T11:00:00",
          username: "Charlie",
          image: "avatar-charlie.jpg",
          message: "I need help with a technical issue."
        },
        {
          time: "2023-10-18T11:10:00",
          username: "David",
          image: "avatar-david.jpg",
          message: "Sure, Charlie. What's the problem you're facing?"
        }
        // Add more messages for the Help channel
      ]
    }
    // Add more channels as needed
  ]
};
```
export default chatData;



if u get stuck anywhere, u can ask as many time u want

**Comment by insane-22** [comment]
Ok, please allow me sometime to try doing the changes, would get back to you in a while.
Thank you for helping so much

**Comment by kabir0x23** [comment]
nice.

one thing

if u do commit and push, ur changes will reflect in this pull request, so u dont have to create another pr for this ..

**Comment by kabir0x23** [comment]
Amazing THanks for your contributions to this community

**Comment by kabir0x23** [comment]
> Hey @kabir0x23 I tried adding the required functionality, this is how it looks now:- image Any other changes?

one sec,. yes one thing left

option to send a message and button at the bottom of the screen

**Comment by insane-22** [comment]
Added it too,
Image demo:- 
image

**Comment by insane-22** [comment]
Would be happy to do further changes/additions?

**Review by kabir0x23 — DISMISSED** [review]
Awesome, thanks for your contribtions

**Comment by insane-22** [comment]
Really enjoyed doing this one! I appreciate your efforts and thank you for giving me this chance to contribute to your project.

**Comment by kabir0x23** [comment]
> Really enjoyed doing this one! I appreciate your efforts and thank you for giving me this chance to contribute to your project.

That's great, welcome and thanks for contribuitions, keep contributing to opensource 👍

**Pull request merged**
