### PR TITLE
Refreshed style changes from reviewed comments on feeds page, #857

### PR DESCRIPTION
**Pull request by alvarotorrestx**
## Fixes Issue

Closes #857 

## Changes proposed

- I had to copy from my original changes due to the commit fixes
- I started off based off what your original style widths were
- Mobile and tablet sized widths have a more single column layout

## Screenshots

https://github.com/thecyberworld/TheCyberHUB/assets/79110517/de4b1086-af6e-4586-b611-54b1bbb7f89c

## Note to reviewers

- I noticed the feed has overflow when at certain widths
- A short term fix was to add overflow: hidden
- Should I start a fix on resizing them? (I'm waiting for your review also to work on this)

## Code of Conduct

-   [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/TheCyberHUB/blob/dev/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

-   [x] My code follows the code style of this project.
-   [ ] My change requires changes to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [x] All new and existing tests passed.
-   [x] This PR does not contain plagiarized content.
-   [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by ArkadiK94** [comment]
## here make the search bar half of the current wide

image

-----

> Should I start a fix on resizing them? (I'm waiting for your review also to work on this)

What do you mean? could you screenshot an example?

**Review by ArkadiK94 — CHANGES_REQUESTED** [review]
Thank you for your contribution, please answer my question in previous message.

**Comment by alvarotorrestx** [comment]
Here is an example, this is on smaller screens. In the screenshot I am turning off the overflow:hidden to show the difference. 
image
image

The same happens at breakpoint w > 950:
image
image

@ArkadiK94

**Comment by ArkadiK94** [comment]
@alvarotorrestx ok, thanks I understand now, yes please fix it. Add word-wrap and so on.

**Comment by alvarotorrestx** [comment]
Will do @ArkadiK94

**Comment by alvarotorrestx** [comment]
Still working on it, slight delay but should have something today.

**Comment by kabir0x23** [comment]
@alvarotorrestx , Hi

can u check if everything is fine on Explorer as well, we are using the same components over there for feeds

and little bit of conflicts are coming can u give a look over there as well

thanks

**Comment by alvarotorrestx** [comment]
> @alvarotorrestx , Hi
> 
> can u check if everything is fine on Explorer as well, we are using the same components over there for feeds
> 
> and little bit of conflicts are coming can u give a look over there as well
> 
> thanks

Yes, that was my original plan to make them both responsive. So I will work on both! 👌

**Comment by alvarotorrestx** [comment]
I wanted an opinion as well before I were to implement it as well for the desktop layout of the Feeds & Explore pages...

Currently Feeds is like this:
image

Explore is like this:
image

Wouldn't it be ideal to possibly swap Feeds reverse? The search bar on the left and the feed on the right? Or vice versa, Explore reversed?

This will help keep a consistent look especially as you add more to the website.

What are your thoughts so I can implement?

**Comment by ArkadiK94** [comment]
@alvarotorrestx In my opinion, it is a great I idea. I would prefer that you will swap inside the Explore page. @kabir0x23 what do you think?

**Comment by kabir0x23** [comment]
yes, we can try with a look

**Comment by alvarotorrestx** [comment]
This would be the updated feeds:
image

This would be the fixed desktop explore page:
image

Resolved the overflow around this width
image

Working on resolving overflows for this along with the below Feeds on the Explore page and the Feeds page:
image
image
image

**Comment by alvarotorrestx** [comment]
Pending commit will be coming, I have saved my progress to work on other device continuously.

**Comment by kabir0x23** [comment]
Hi, you try to move it sidebar to  right side?

**Comment by alvarotorrestx** [comment]
Sorry, so you want them like this?

image

image

**Comment by kabir0x23** [comment]
looks good

**Comment by ArkadiK94** [comment]
@alvarotorrestx hi, any update?

**Comment by alvarotorrestx** [comment]
@ArkadiK94 Hey there, I'm so sorry. I've fallen behind on a lot of my open source work because I've been helping my mother who just recently had surgery. If you'd like I can submit my most recent updates that I had when I get on my home computer. I can try to get it completed this week or you can re-assign. I completely understand.

**Comment by alvarotorrestx** [comment]
@ArkadiK94 Thanks, I appreciate that. Yes, I will submit what I've done later today and you can re-assign. That way I don't keep you waiting. I will take a look at other issues hopefully soon to help continue to contribute. 👍

**Comment by alvarotorrestx** [comment]
@ArkadiK94 submitted what I had, thank you!

**Pull request closed without merging**
