### PR TITLE
fix: AIChat responsive fix - cherry pick of pr 844

### LINKED ISSUE #805: [Responsive-Web] AI new chat section is not responsive
### Detailed description

AI new chat section is not responsive.

On big screen design is not appropriate

image

### To Reproduce

-

### Expected Behavior

-

### Screenshot/ Video of the Responsive Problem

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ArkadiK94**
## Fixes Issue
Closes #805 

## Changes proposed
- added overflow on chat content
- recent chat box moved to absolute positioning under 800px to avoid overcrowding on mobile devices
- overlapping grid styles in Prompts component removed

## Screenshots
[337881101-7dbfa97c-07a9-4375-956f-68fceb7f6f97.webm](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/c70f0124-2d65-47fb-8691-5d155448bc31)

## Note to reviewers
done by @SinanovicAhmed 
It is a cherry pick duo to changed dev branch

## Code of Conduct

-   [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/TheCyberHUB/blob/dev/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

-   [x] My code follows the code style of this project.
-   [ ] My change requires changes to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [x] All new and existing tests passed.
-   [x] This PR does not contain plagiarized content.
-   [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by ArkadiK94** [comment]
@SinanovicAhmed Thanks for contributing, I have some comments. 
Before the comments, notice the next important note:

The dev branch is a new branch which was changed due to repo technical errors 

What you need to do:
Step one in github:
Go to local repo
Click "Synk fork"
Click Discard <Number> Commits/Changes

Step two in local editor:
You will notice a number of commits that it wants to push let's call it <X>
In terminal:
git reset HEAD~<X>
git pull 

If you would like to solve the comments you should do them in this branch:
gh pr checkout 855

Sorry for this scenario, it is not something that happens often.

**Comment by ArkadiK94** [comment]
1.
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/35d11e90-c681-45c0-a0de-a7bdbf6143d4

In some widths it is still not responsive as needed

2.

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/e8814e57-fc7c-463d-803e-a5b721b64670

@kabir0x23 what do you think about this way that the left menu opens? I think it is ok, however, maybe better on clicking the icon, the left menu will slide to right and the right menu will not be displayed

3.
image
image
image


Tell me that you see this black border and black lines, please, remove them.

**Comment by SinanovicAhmed** [comment]
@ArkadiK94 I fixed points 1 and 2, but I couldn't get the black borders and lines to appear from point 3.

**Comment by ArkadiK94** [comment]
@SinanovicAhmed what do you mean? don't you see them or you could not find the reason for them?

**Comment by SinanovicAhmed** [comment]
@ArkadiK94 I can see the lines in the image you provided, but they don't appear when I run the project locally.  Are they always there or when you do specific action they appear?

**Comment by ArkadiK94** [comment]
@SinanovicAhmed When I click around the arrow btn.

**Comment by SinanovicAhmed** [comment]
@ArkadiK94 Me mindlessly clicking around arrow button 😄 
 
[screen-capture (3).webm](https://github.com/thecyberworld/TheCyberHUB/assets/93159428/00c46a24-dbee-4626-bbb8-c124001e76d0)

**Comment by ArkadiK94** [comment]
@SinanovicAhmed Haha, please, push the changes maybe it was fixed 😅 I will check and let you know :)

**Comment by SinanovicAhmed** [comment]
@ArkadiK94 I was working directly on cherry-pick/pr-844 branch because I wasn't familiar with "gh pr checkout 855" command you mentioned. Should be ok to  push changes to that branch?

**Comment by ArkadiK94** [comment]
@SinanovicAhmed Your work-around is a great idea :)

**Comment by ArkadiK94** [comment]
image

about black lines, I use Firefox browser, maybe it is related, you can leave it for now.
however, I didn't line that when you click it slides inside the "New Chat" In my opinion, it should be instead.

**Comment by ArkadiK94** [comment]
@SinanovicAhmed Hi, how is it going?

**Comment by SinanovicAhmed** [comment]
> @SinanovicAhmed Hi, how is it going?

Hi, I wasn't really looking into it so far. So you want on smaller devices only one window to be open and on larger they can both be open at the same time? I haven't tried to fix it yet but it seems to be decent amount of work for minimal change in my opinion. I can work on it when I get the time if it's 100% what you need.

**Comment by ArkadiK94** [comment]
@SinanovicAhmed ok, I will merge it and we will handle this later. Thanks for your contribution.

**Pull request merged**
