### PR TITLE
feat: notifications | Added notification toggle buttons

### LINKED ISSUE #653: [FEATURE] Add checkbox/notifications option to user to choose get notified
### Detailed description

We need to add it in settings > notifications like a toggle buttons for every thing that the user can be notified about 
all toggle, events toggle,  newsletter toggle, blogs toggle,  and so on.

https://dev.thecyberhub.org/#/dashboard/settings/profile

### Context

Users could have flexibility on the things that they would like to be notified about.

### Possible implementation

This is an example make it for notifications: title "Notifications" , toggle buttons the things that the user could be notified about.
* when the user will register and check the box to get notified the status of all those buttons will be on, and if they will not check the box the default of all will be off.

303906806-6ce95612-39a5-4349-8bac-2d5d443cf88d

### Additional information

@Happyashbunny I created a new issue about this. Do you have some questions about the implementation?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Happyashbunny**
Resolves #653 

@ArkadiK94 

I've added toggle buttons to the 'notifications' section in settings. These are currently just for show and don't have functionality. 

Notifications off
Screenshot 2024-02-15 233033

Notifications on
Screenshot 2024-02-16 085119

I wanted to know whether we should include an all notifications button or not. And if we are to include it then, should we make it such that upon clicking 'all' the remaining options toggle to 'off' by themselves. 

I am also sorry for the delay

### CODE REVIEW

**Comment by ArkadiK94** [comment]
@Happyashbunny Hi, as I see it, I think it is a great idea to include "all" button but it will work differently. 
When you turn it on all other buttons will be turned on automatically. 
When you turn it off , it will not effect any of the other buttons. 
When you turn off at least one of the other buttons, it will turn "all" button off as well.

**Comment by ArkadiK94** [comment]
@Happyashbunny In addition, make the "all" button stand out from others, bigger font test and bigger button size.

**Comment by ArkadiK94** [comment]
>@Happyashbunny Hi, as I see it, I think it is a great idea to include "all" button but it will work differently.
When you turn it on all other buttons will be turned on automatically.
When you turn it off , it will not effect any of the other buttons.
When you turn off at least one of the other buttons, it will turn "all" button off as well.

>@Happyashbunny In addition, make the "all" button stand out from others, bigger font test and bigger button size.

@Happyashbunny Would you like to do the changes in this pr? or can I review it and you will implement those changes in a different pr ?

**Comment by Happyashbunny** [comment]
@ArkadiK94 either way works for me.

**Comment by Happyashbunny** [comment]
> @ArkadiK94 either way works for me.

Also I've incorporated the changes you asked me to make. Lemme know if I should make another PR.

**Comment by ArkadiK94** [comment]
If you already did the changes you can push them to this pr.

**Comment by Happyashbunny** [comment]
@ArkadiK94 I've made the 'all' button bigger and implemented other minor functionalities

Currently I haven't linked it to the checkbox in the registration page, 

However the buttons do change the state and function as you wanted them to. 

Before
Screenshot 2024-02-17 142452

Upon clicking the 'all' button all the other ones turn 'on' by themselves
Screenshot 2024-02-17 142501

Upon clicking any button other than 'all' button, the 'all' button turns off by itself. 
Screenshot 2024-02-17 165945

And turning off the 'all' button doesn't bring any changes to the other buttons. I'm sure other changes are to be made so let me know what they are.

**Comment by ArkadiK94** [comment]
@Happyashbunny Great work, looks amazing 👏

**Pull request merged**
