### PR TITLE
Added feature Victim Help

### LINKED ISSUE #501: [FEATURE] Add a new page for - If someone gets scammed, those gov links to help them should be mentioned in that page.
### Detailed description

[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

If someone gets scammed, those gov links to help them should be mentioned in that page.

### Context

This will help those got scammed

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ezhillragesh**
## Fixes Issue
Close #501 

## Changes proposed
 Added a new page Victim Help

## Screenshots

image
image

## Code of Conduct

- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by kabir0x23** [comment]
hey, can u change the branch to dev branch,i am not able to do?

and you worked on dev branch right?

**Comment by ezhillragesh** [comment]
> hey, can u change the branch to dev branch,i am not able to do?
> 
> and you worked on dev branch right?

yup I worked in dev branch , when i try to move the PR to dev branch I get this:
image

**Comment by ezhillragesh** [comment]
> > hey, can u change the branch to dev branch,i am not able to do?
> > and you worked on dev branch right?
> 
> yup I worked in dev branch , when i try to move the PR to dev branch I get this: image

I tried making a new PR to dev branch  but it is not showing any differences: 
image
but when I check with the status in my local machine there exist changes :
image
what should do ? any idea?

**Comment by ezhillragesh** [comment]
> @ezhillragesh hi
hello

**Pull request closed without merging**
