### PR TITLE
Fixes the card design on smaller breakpoints 

### LINKED ISSUE #453: [BUG] In mobile view the community links cards are not looking good
### Describe the bug

[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

In each card the text and icon should be in a row but they are in a column. I think we should fix them as soon as we can.
Kindly assign this issue to me so that I can fix this.

### To Reproduce

Set the display to flex

### Expected Behavior

The text and icon should be in a row

### Screenshot/ Video

Screenshot_20231002-070056

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by itsankitbhusal**
## Fixes Issue
Closes #453 

## Changes proposed

- Centered the social media icon and name inside the card in a smaller viewport (smaller than 780px)

## Screenshots
Screenshot from 2023-10-11 16-29-20
Screenshot from 2023-10-11 16-29-53
Screenshot from 2023-10-11 16-30-29

## Note to reviewers
I think the card looks better in 2 rows (icon in first row and name in second row) than in the column.
I have centered the card elements on smaller devices size smaller size(780px)

If this is strictly needed in a column, you can mention it, but I think centering the card elements on a smaller screen will work.

## Code of Conduct

- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by itsankitbhusal** [comment]
I don't know why the **already merged** commits are also shown as a changed file.
The changed file is only `src/components/Homepage/Socials/SocialsElements.jsx`

**Comment by itsankitbhusal** [comment]
@kabir0x23 why are the already merged files also getting shown in the pull request?

also, tell me if the design on smaller screens is good or if I need to make some changes.

**Comment by kabir0x23** [comment]
> I don't know why the **already merged** commits are also shown as a changed file. The changed file is only `src/components/Homepage/Socials/SocialsElements.jsx`

because when we work on new issue, always create a new branch from the main/dev branch 

if we work on same branch or creates a branch from already submiited branch, then it will again show those commits and will give conflicts/errors

**Comment by itsankitbhusal** [comment]
Does it mean I need to again clone the repo each time or does just creating the branch work? @kabir0x23 
Do I need to make a new pull request now form a different branch closing this?

**Comment by kabir0x23** [comment]
> Does it mean I need to again clone the repo each time or does just creating the branch work? @kabir0x23 Do I need to make a new pull request now form a different branch closing this?

once u have submitted the code / pr
go to your project, change the branch back the main/dev
then create a new branch from it (if the pr gets merged, u will get your changes back with main/dev, if it does't, don't worry that changes nothing.)

**Comment by kabir0x23** [comment]
as of now, just copy ur changes into another file on your computer,

and do the same process, create a new branch from dev, and then copy ur changes hhere

**Comment by itsankitbhusal** [comment]
before making changes I've already done `git pull origin main` and `git pull origin dev` and I started doing the changes, 
In this process where I have been mistaken?

> > Does it mean I need to again clone the repo each time or does just creating the branch work? @kabir0x23 Do I need to make a new pull request now form a different branch closing this?
> 
> once u have submitted the code / pr go to your project, change the branch back the main/dev then create a new branch from it (if the pr gets merged, u will get your changes back with main/dev, if it does't, don't worry that changes nothing.)

**Comment by kabir0x23** [comment]
> before making changes I've already done `git pull origin main` and `git pull origin dev` and I started doing the changes, In this process where I have been mistaken?
> 
> > > Does it mean I need to again clone the repo each time or does just creating the branch work? @kabir0x23 Do I need to make a new pull request now form a different branch closing this?
> > 
> > 
> > once u have submitted the code / pr go to your project, change the branch back the main/dev then create a new branch from it (if the pr gets merged, u will get your changes back with main/dev, if it does't, don't worry that changes nothing.)

have u created a new branch from dev again?

**Comment by itsankitbhusal** [comment]
> > before making changes I've already done `git pull origin main` and `git pull origin dev` and I started doing the changes, In this process where I have been mistaken?
> > > > Does it mean I need to again clone the repo each time or does just creating the branch work? @kabir0x23 Do I need to make a new pull request now form a different branch closing this?
> > > 
> > > 
> > > once u have submitted the code / pr go to your project, change the branch back the main/dev then create a new branch from it (if the pr gets merged, u will get your changes back with main/dev, if it does't, don't worry that changes nothing.)
> 
> have u created a new branch from dev again?

no no before working on this new issue,  I have used these two commands, and then started work on dev branch not new branch

**Comment by kabir0x23** [comment]
yes, that's why it caused an issue, make sure to create new branch always, with respective issue name so it will be easy to manag
e

**Comment by itsankitbhusal** [comment]
@kabir0x23 the issue is now resolved and only showed the changed file.
The problem was I synced the main branch only, now after syncing the dev branch the issue is now resolved.

Now have a look at the code and mention if any design changes are needed in the socials card layout.

**Pull request merged**
