### PR TITLE
feat: profile | auth popup on follow/connect when no user / connection request styling overflow

### PR DESCRIPTION
**Pull request by 92206**
fixes issue #603 

## Changes proposed

- fixed the connection request overflow  

- add auth popup when clicking follow or connect and no user is logged in : 

## Screenshots

image

image

## Note to reviewers

although in this issue it was asked to show a login popup for non logged in users who click on follow , i added the same functionality for the connect button .

## Code of Conduct

- [ x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [x ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by kabir0x23** [comment]
this looks wierd, 

do one thing
image


1. can u try all of three in column, with full width

2. follow with ful width, wil accept and rejectoin below like same as above image, just remove request text in both/


can u share both changes and share screenshot?

Thank you

**Comment by 92206** [comment]
Im not sure i understand .
. Should i try to make them all in one line filling the container width like this : 
/follow/accept/reject .

**Comment by ArkadiK94** [comment]
@92206  About what Kabir suggested , I created something in Figma only for illustration.
@kabir0x23 which one do you prefer?
1. 
image
2.
image

**Comment by kabir0x23** [comment]
@ArkadiK94 second is good, what do you think?

**Comment by ArkadiK94** [comment]
I agree

**Comment by 92206** [comment]
these are the screenshots for the result  : 
image
image

**Comment by ArkadiK94** [comment]
@92206 Looks way better, but please, adjust all the buttons and loading spinner to fit the new design

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/d0fe1391-2b6d-4fe1-8c69-d83f9ef049e8

Screenshot 2024-02-02 165022
Screenshot 2024-02-02 165103

**Review by ArkadiK94 — DISMISSED** [review]
Thanks for your contribution, adjust the width of the buttons and the spinner so we could merge this pr.

**Comment by 92206** [comment]
@ArkadiK94  send me a request one last time if you yould at "slouma"

**Comment by ArkadiK94** [comment]
@92206 I sent you a request. By the way, what I did , I created two accounts so I could test it properly :)

**Comment by ArkadiK94** [comment]
@92206 Hi, I saw that you pushed new changes, is it still in progress? Or is it ready for review?

**Comment by 92206** [comment]
> @92206 Hi, I saw that you pushed new changes, is it still in progress? Or is it ready for review?

Yes its ready

**Review by ArkadiK94 — APPROVED** [review]
@92206 Looks awesome, thanks you very much for your contribution 💯

**Pull request merged**
