### PR TITLE
feat: sponsors page

### LINKED ISSUE #502: [FEATURE] Add a sponsor page.
### Detailed description

[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

example: https://vitejs.dev/
image

### Context

.

### Possible implementation

_No response_

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by shagundubey29**
Closes #502

## Changes proposed

I have added Sponsors section below the Community Link section.

## Screenshots

[screen-capture.webm](https://github.com/thecyberworld/TheCyberHUB/assets/89803512/3b6885b7-af78-40bb-ab16-61087a5d90c2)
Screenshot (207)
Screenshot (208)

## Note to reviewers

I have designed the hover state for both sponsor logos, or if you don't have any, you can simply use text. I have designed both components.

## Code of Conduct

- [X] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by kabir0x23** [comment]
amazing, 

and u have missed installation guide, right?

**Comment by shagundubey29** [comment]
Actually, I was switching to the dev branch, but it was not happening. Otherwise, I have followed the installation guide.

**Comment by kabir0x23** [comment]
> Actually, I was switching to the dev branch, but it was not happening. Otherwise, I have followed the installation guide.

u have missed the very first step
image

of uncheck that box

**Review by kabir0x23 — DISMISSED** [review]
Thanks for your contributions to this community

**Comment by shagundubey29** [comment]
Your welcome.

**Pull request merged**
