### PR TITLE
added quiz-new version updated

### PR DESCRIPTION
**Pull request by priyanshtiwari001**
### Changes:

- when we entered in the Quiz page, We directly getting the quiz question so I added a Quiz start section where when we entered in Quiz page. We get a start now option so that we can start the quiz.
- Added the progress bar rather than Dot bar.
- I  also made changes in the color scheme in Quiz page. As when we hover the option we got green color that doesn't follow the site color scheme so I changes that to ff6b07(orange) .

# Screenshots

## Quiz Start page

Screenshot 2023-10-10 at 11 11 39 PM

## Add Progress bar and color scheme improvement

Screenshot 2023-10-10 at 11 13 22 PM

## Code of Conduct

- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Review by kabir0x23 — CHANGES_REQUESTED** [review]
Hey,

Thanks for the contributing to Thecyberworld Community

Can we do same changes?

Example, in the home screen of quizes we can show big cards (sample example u can see roadmaps section)
```
- - -
- - -
- - -
```

when someone click on those card/title, then it should be shown

now we just have to bigger the size of title from homepage

If u are having any questions or doubts, feel free to ask below
Thank you

**Comment by priyanshtiwari001** [comment]
Hi, from what I understand, do you want the category section to be turned into a card section, similar to the roadmap? And after that, do you want quiz questions? Also, the changes I made will appear after the card section, based on the category chosen, such as basic, phishing, etc. Is that correct?

**Comment by kabir0x23** [comment]
> Hi, from what I understand, do you want the category section to be turned into a card section, similar to the roadmap? And after that, do you want quiz questions? Also, the changes I made will appear after the card section, based on the category chosen, such as basic, phishing, etc. Is that correct?

Yes, right, when we click on particular card, it should open those quizes,

optional: (or u can create new issue based on this.)
we also can use router or url based example
even if someone paste that particualr url quiz, it should open those

quiz/phishing

it should open phishing too

**Comment by priyanshtiwari001** [comment]
I like to create a new issue and want close the issue if you are good with that. I will update all the details in new issue.

**Review by kabir0x23 — APPROVED** [review]
Thanks for contributing to Thecyberworld Community

**Pull request merged**
