### PR TITLE
Explore | Combine all the empty data fields

### LINKED ISSUE #690: [FEATURE] Explore | Combine all the empty data fields
### Detailed description

In Explore, when there are not some data , we will have an block with "Not Found" message, for example if there are not blogs and ctfs we will have something like this:

image

need to combine to one "Not Found" message

### Context

To much repetitive info

### Possible implementation

minimize all the block texts to one generic that will indicate all the "Not Found", example: User Details, Feeds, Blogs, Not Found (in case there are not user details , feeds or blogs) and if we have Ctfs the "Not Found" message will be blow the Ctf data.

### Additional information

if you have any question , feel free to ask :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Som401**
## Fixes Issue
Closes #690

## Changes proposed
This pull request fixes an issue in the Explore section. Previously, selecting 'all' filter with no items available displayed 'Not Found' message four times. 

Changes:
1. Moved the empty list check to the Explore component. It now checks if all item lists are empty and displays a single 'Not Found' message if true.

This change provides a cleaner interface when no items are available.

## Code of Conduct

- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by ArkadiK94** [comment]
@Som401 Hi, you handled only one case: when all data not found , the user will see only one Not Found message. However, you didn't combine cases when for example there are user details and blogs but there are not feeds and ctf , the user also should see only one message of Not Found : "Ctf and Feeds Not Found" - below the data.

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/f551b930-2571-4d3b-8517-92f0105b3b32

**Comment by Som401** [comment]
@ArkadiK94  I implemented a new function called renderNotFoundComponents, this function utilizes a string builder approach to construct the description for the NotFound component. It efficiently handles different scenarios, including when all data types are missing or when there are some missing data types.

**Comment by ArkadiK94** [comment]
@Som401 you didn't handle something right, there are some errors.

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/7dae6dd9-a7bf-454b-86ba-3e0164a810c4

**Comment by ArkadiK94** [comment]
@Som401 It is not related to you, I will handle it...

**Pull request merged**
