### PR TITLE
 feat: notes | Multiple Categories deletion feature  - cherry pick of pr 770

### PR DESCRIPTION
**Pull request by ArkadiK94**
## Fixes Issue
cherry pick of pr #770 see there all the relevant comments

## Note to reviewers
done by @Jazzxe

## Code of Conduct

-   [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/TheCyberHUB/blob/dev/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

-   [x] My code follows the code style of this project.
-   [ ] My change requires changes to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [x] All new and existing tests passed.
-   [x] This PR does not contain plagiarized content.
-   [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by ArkadiK94** [comment]
I am changing to draft until it will be ready for review

**Comment by ArkadiK94** [comment]
@kabir0x23 I fixed the comments that I left when I did cr in pr #770.
I also did some changes, could you please review it?

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/8ba7ed5c-93b9-4431-bc73-4c98582e307a

**Review by kabir0x23 — APPROVED** [review]
nice, looks good

**Comment by kabir0x23** [comment]
@ArkadiK94 conflicts

**Comment by ArkadiK94** [comment]
> nice, looks good

@kabir0x23 ok, so I handled conflict and I merge it

**Pull request merged**
