### PR TITLE
[BUG] Fixed feed post design in explore section, {branch: dev}.

### LINKED ISSUE #476: [BUG] fix fead post design in explore section, {branch: dev}.
### Describe the bug

[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

url: https://dev.thecyberhub.org/#/explore
image

as we can see the height of the other feeds depending on the max height feed
fix: it is fine in row. but looking bad in column, exmaple 3rd feed height should be it's own, instead of above feed heights 

### To Reproduce

go to: https://dev.thecyberhub.org/#/explore

### Expected Behavior

_No response_

### Screenshot/ Video

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 0xlarmideh**
## Fixes Issue

Closes #476

## Changes proposed

Fixed bug in card rows taking height of the maximum content in the grid. The Row height is now defined by the max-content of a card inside the row as opposed to the whole grid.

## Screenshots

image

## Code of Conduct

- [X] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by kabir0x23** [comment]
Looks like haven't gone through the installation guide, right?

**Comment by 0xlarmideh** [comment]
Is there an issue.....I went through the contribution and installation guide.

Let me know if there's an issue

**Comment by kabir0x23** [comment]
> Is there an issue.....I went through the contribution and installation guide.
> 
> Let me know if there's an issue @kabir0x23

this is the  [Installation guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

u can remove this fork
and thne u can follow this installtion 

actually we are working on dev branch, as u have made a branch from main, it contains some changes 

so u have to do that with forking with dev branch, and creating a new branch form it.

**Comment by 0xlarmideh** [comment]
@kabir0x23 Do I need to go through this Contribution guide https://github.com/thecyberworld/TheCyberHUB/blob/dev/CONTRIBUTING.md or I can just pull from dev, make my changes and stage my files?
When I followed the contribution guide, there were some conflicts even when I havent made any edit

**Comment by kabir0x23** [comment]
> @kabir0x23 Do I need to go through this Contribution guide https://github.com/thecyberworld/TheCyberHUB/blob/dev/CONTRIBUTING.md or I can just pull from dev, make my changes and stage my files? When I followed the contribution guide, there were some conflicts even when I havent made any edit

yes, because u have crated branch from main,now u have to create from dev this time..

**Comment by kabir0x23** [comment]
> > @kabir0x23 Do I need to go through this Contribution guide https://github.com/thecyberworld/TheCyberHUB/blob/dev/CONTRIBUTING.md or I can just pull from dev, make my changes and stage my files? When I followed the contribution guide, there were some conflicts even when I havent made any edit
> 
> yes, because u have crated branch from main,now u have to create from dev this time..

u can pull if it is possible, because u only have forked main branch

**Pull request closed without merging**
