### PR TITLE
feat: Feeds | Implement Multiple Tag Filtering Functionality

### PR DESCRIPTION
**Pull request by Som401**
## Fixes Issue
#626

## Changes proposed
This pull request addresses the issue of enhancing tag filtering functionality in the Feeds section to allow users to filter posts by multiple tags simultaneously. 

## Screenshots

https://github.com/thecyberworld/TheCyberHUB/assets/147496504/c6f2eb17-5f9e-43bc-b7ad-e9ce8dc5b415

## Note to reviewers
In the video, there are more tags available for experimentation compared to the tags present in the development environment. Please note that I've added these additional tags just  for testing purposes but did not include them in the final commit for this pull request. 

## Code of Conduct

- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/Support/blob/main/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by ArkadiK94** [comment]
@Som401 The video is not working :(

image

**Comment by ArkadiK94** [comment]
@Som401 on mobile the video is working. Could you add also a clear button so if the users would like to clear all tags together at one click, they could do it.

**Comment by Som401** [comment]
@ArkadiK94 I've added the clear icon to the search bar. Could you review and confirm if it's okay?
https://github.com/thecyberworld/TheCyberHUB/assets/147496504/cbed96d8-847f-462d-9cfa-ba0e72cf032c

**Review by ArkadiK94 — APPROVED** [review]
Awesome work with all the `zero width space` (I tried to understand the concept and I need more time for it haha), thank you very much for your contribution. I have minor comments.

**Comment by Som401** [comment]
> Awesome work with all the `zero width space` (I tried to understand the concept and I need more time for it haha), thank you very much for your contribution. I have minor comments.

@ArkadiK94 I've addressed all the minor changes you suggested, everything should be good to go now, please take another look when you have a moment.

**Comment by ArkadiK94** [comment]
@Som401 Thank you, looks great.

**Pull request merged**
