### PR TITLE
docs: Change broken coc url

### LINKED ISSUE #749: [BUG] Code of conduct not found
### Describe the bug

When you open a new pr you are suggested to go to the code of conduct, currently its not found

### To Reproduce

Open new pr, you will see this : 

image

### Expected Behavior

The link should redirect to the project code of conduct

### Screenshot/ Video

Instead, this is what we see : 

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Tamir198**
close #749 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by ArkadiK94** [comment]
@Tamir198 could you change in all the templates as well? 
When we create a new template there also we have this redirection to coc and it doesn't work there as well.

**Comment by Tamir198** [comment]
Ye sure i will add it into the pr

**Comment by Tamir198** [comment]
@ArkadiK94  Changed, if I missed some templates tell me and I will add the changes as well?

**Review by ArkadiK94 — APPROVED** [review]
@Tamir198 Thanks for your contribution, yes, you made changes in all relevant places.

**Pull request merged**
